apiVersion: v1
kind: Namespace
metadata:
  namespace: offensive-web-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sa
  namespace: offensive-web-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-sa-clusterrolebinding
  namespace: offensive-web-app
subjects:
- kind: ServiceAccount
  name: secret-sa
  namespace: offensive-web-app
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: secret-role
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-role
  namespace: offensive-web-app
rules:
- apiGroups: ["*"]
  resources: ["serviceaccounts","serviceaccounts/token"]
  verbs: ["*"]
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: offensive-web-app
  name: offensive-web-app
  namespace: offensive-web-app
spec:
  replicas: 1
  selector:
    name: offensive-web-app
  template:
    metadata:
      labels:
        name: offensive-web-app
    spec:
      serviceAccountName: secret-sa
      containers:
      - image: chrisley75/offensive-web-appp:0.0.1
        name: vul-offensive-web-app
        ports:
        - containerPort: 8080
          name: http-server
---
apiVersion: v1
kind: Service
metadata:
  name: offensive-web-app-svc
  namespace: offensive-web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: offensive-web-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  namespace: offensive-web-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: cluster-admin-sa
  namespace: offensive-web-app
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""